Repository cmpsr/composer, pull requests merged in 2020-08, with the labels that each got.

#104 Call identify on analytics object
  .changeset/strange-guests-watch.md
  packages/analytics/lib/integrations/segment/Segment.js
  packages/analytics/src/integrations/segment/Segment.ts
Labels: bug, ready for review

#111 Style Guide Colors - Fix Borders
  .changeset/twelve-tomatoes-smell.md
  packages/components/lib/components/primitives/form/CurrencyField/CurrencyField.js
  packages/components/lib/components/primitives/form/CurrencyFieldIcon/CurrencyFieldIcon.js
  packages/components/lib/utils/getDropdownSingleSelectClasses/index.d.ts.map
  packages/components/lib/utils/getDropdownSingleSelectClasses/index.js
  packages/components/lib/utils/getTextFieldStateClasses/index.d.ts.map
  packages/components/lib/utils/getTextFieldStateClasses/index.js
  packages/components/src/components/layouts/forms/Login/__snapshots__/Login.test.tsx.snap
  packages/components/src/components/primitives/form/CurrencyField/CurrencyField.tsx
  packages/components/src/components/primitives/form/CurrencyFieldIcon/CurrencyFieldIcon.tsx
  packages/components/src/components/primitives/form/DropdownField/DropdownDownshiftSelect/DropdownDownshiftSelect.test.tsx
  packages/components/src/components/primitives/form/DropdownField/DropdownNativeSelect/DropdownNativeSelect.test.tsx
  packages/components/src/utils/getDropdownSingleSelectClasses/index.ts
  packages/components/src/utils/getMessageClasses/index.test.ts
  packages/components/src/utils/getTextFieldStateClasses/index.test.ts
  packages/components/src/utils/getTextFieldStateClasses/index.ts
Labels: bug, ready for review

#113 React popper tooltip
  .changeset/funny-moles-sip.md
  packages/components/lib/components/primitives/Tooltip/Tooltip.css
  packages/components/lib/components/primitives/Tooltip/Tooltip.d.ts
  packages/components/lib/components/primitives/Tooltip/Tooltip.d.ts.map
  packages/components/lib/components/primitives/Tooltip/Tooltip.js
  packages/components/lib/components/primitives/Tooltip/Tooltip.styles.d.ts
  packages/components/lib/components/primitives/Tooltip/Tooltip.styles.d.ts.map
  packages/components/lib/components/primitives/Tooltip/Tooltip.styles.js
  packages/components/lib/components/primitives/Tooltip/stories/Tooltip.stories.js
  packages/components/lib/styles/index.css
  packages/components/lib/styles/plugins.js
  packages/components/lib/styles/pseudoElements.js
  packages/components/lib/styles/theme.js
  packages/components/lib/styles/variants.js
  packages/components/package.json
  packages/components/src/components/primitives/Tooltip/Tooltip.css
  packages/components/src/components/primitives/Tooltip/Tooltip.styles.tsx
  packages/components/src/components/primitives/Tooltip/Tooltip.test.tsx
  packages/components/src/components/primitives/Tooltip/Tooltip.tsx
  packages/components/src/components/primitives/Tooltip/index.ts
  packages/components/src/components/primitives/Tooltip/stories/Tooltip.stories.tsx
  packages/components/src/styles/index.css
  packages/components/src/styles/plugins.js
  packages/components/src/styles/pseudoElements.js
  packages/components/src/styles/theme.js
  packages/components/src/styles/variants.js
  yarn.lock
Labels: ready for review

#117 Use colors file generated by sketch plugin
  .changeset/chatty-turtles-cry.md
  packages/components/lib/components/primitives/form/RadioButton/RadioButton.css
  packages/components/lib/styles/colors.js
  packages/components/lib/styles/customForms.js
  packages/components/lib/styles/theme.js
  packages/components/lib/utils/getButtonStateClassesFromType/index.js
  packages/components/lib/utils/getDropdownClasses/index.js
  packages/components/lib/utils/getDropdownSingleSelectClasses/index.js
  packages/components/lib/utils/getRadioButtonClasses/index.js
  packages/components/src/components/layouts/forms/Login/__snapshots__/Login.test.tsx.snap
  packages/components/src/components/primitives/Button/Button.test.tsx
  packages/components/src/components/primitives/form/RadioButton/RadioButton.css
  packages/components/src/styles/colors.js
  packages/components/src/styles/customForms.js
  packages/components/src/styles/theme.js
  packages/components/src/utils/getButtonStateClassesFromType/index.test.ts
  packages/components/src/utils/getButtonStateClassesFromType/index.ts
  packages/components/src/utils/getDropdownClasses/index.test.ts
  packages/components/src/utils/getDropdownClasses/index.ts
  packages/components/src/utils/getDropdownSingleSelectClasses/index.ts
  packages/components/src/utils/getRadioButtonClasses/index.ts
Labels: enhancement, ready for review

#119 Update typographies tokens to match DSM definition
  .changeset/sweet-camels-tan.md
  packages/components/lib/components/primitives/Typography/Typography.css
  packages/components/lib/components/primitives/form/form.css
  packages/components/lib/styles/theme.js
  packages/components/src/components/primitives/Typography/Typography.css
  packages/components/src/components/primitives/form/form.css
  packages/components/src/styles/theme.js
Labels: ready for review

#131 Check for undefined value
  .changeset/chilly-cows-relax.md
  packages/firestore/src/db/FirestoreDb.test.ts
  packages/firestore/src/db/FirestoreDb.ts
Labels: ready for review

#130 Publish packages with fixed vulnerabilities
  .changeset/warm-humans-cheer.md
  yarn.lock
Labels: ready for review
