Repository cmpsr/composer, pull requests merged in 2020-07, with the labels that each got.

#63 Snackbar
  .changeset/tall-queens-travel.md
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.d.ts
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.d.ts.map
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.js
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.stories.js
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.styles.d.ts
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.styles.d.ts.map
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.styles.js
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/index.d.ts
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/index.d.ts.map
  packages/components/lib/components/primitives/Snackbar/DefaultSnackbar/index.js
  packages/components/lib/styles/index.css
  packages/components/lib/styles/theme.js
  packages/components/lib/styles/variants.js
  packages/components/package.json
  packages/components/src/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.stories.tsx
  packages/components/src/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.styles.ts
  packages/components/src/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.test.tsx
  packages/components/src/components/primitives/Snackbar/DefaultSnackbar/DefaultSnackbar.tsx
  packages/components/src/components/primitives/Snackbar/DefaultSnackbar/index.ts
  packages/components/src/styles/index.css
  packages/components/src/styles/theme.js
  packages/components/src/styles/variants.js
  yarn.lock
Labels: ready for review

#71 Snackbar - onClose callback
  .changeset/fresh-knives-pretend.md
  packages/components/lib/components/primitives/Snackbar/Snackbar.d.ts
  packages/components/lib/components/primitives/Snackbar/Snackbar.d.ts.map
  packages/components/lib/components/primitives/Snackbar/Snackbar.js
  packages/components/lib/components/primitives/Snackbar/Snackbar.stories.js
  packages/components/src/components/primitives/Snackbar/Snackbar.stories.tsx
  packages/components/src/components/primitives/Snackbar/Snackbar.tsx
Labels: ready for review

#75 Modal - overlayClassName
  .changeset/mighty-queens-cough.md
  packages/components/lib/components/primitives/Modal/Modal.d.ts
  packages/components/lib/components/primitives/Modal/Modal.d.ts.map
  packages/components/lib/components/primitives/Modal/Modal.js
  packages/components/src/components/primitives/Modal/Modal.test.tsx
  packages/components/src/components/primitives/Modal/Modal.tsx
Labels: ready for review

#79 Snackbar fix styles
  .changeset/little-masks-sparkle.md
  packages/components/lib/components/primitives/Snackbar/Snackbar.css
  packages/components/lib/components/primitives/Snackbar/Snackbar.d.ts.map
  packages/components/lib/components/primitives/Snackbar/Snackbar.js
  packages/components/lib/styles/index.css
  packages/components/src/components/primitives/Snackbar/Snackbar.css
  packages/components/src/components/primitives/Snackbar/Snackbar.tsx
  packages/components/src/styles/index.css
Labels: ready for review

#81 Conversation summary fix
  .changeset/neat-hounds-talk.md
  packages/components/lib/components/primitives/Chat/ConversationList/stories/ConversationList.stories.js
  packages/components/lib/styles/theme.js
  packages/components/lib/utils/getConversationSummaryClasses/index.js
  packages/components/src/components/primitives/Chat/ConversationList/stories/ConversationList.stories.tsx
  packages/components/src/styles/theme.js
  packages/components/src/utils/getConversationSummaryClasses/index.test.ts
  packages/components/src/utils/getConversationSummaryClasses/index.ts
Labels: ready for review

#83 New Snackbar implementation
  .changeset/gold-files-reply.md
  packages/components/lib/components/primitives/Snackbar/Snackbar.d.ts
  packages/components/lib/components/primitives/Snackbar/Snackbar.d.ts.map
  packages/components/lib/components/primitives/Snackbar/Snackbar.js
  packages/components/lib/components/primitives/Snackbar/Snackbar.stories.js
  packages/components/src/components/primitives/Snackbar/Snackbar.stories.tsx
  packages/components/src/components/primitives/Snackbar/Snackbar.test.tsx
  packages/components/src/components/primitives/Snackbar/Snackbar.tsx
Labels: enhancement, ready for review

#88 Add auth google cloud kms integration
  .changeset/cuddly-rules-join.md
  packages/cloud-kms/src/Kms.test.ts
  packages/cloud-kms/src/Kms.ts
  packages/cloud-kms/src/index.test.ts
  packages/cloud-kms/src/index.ts
  packages/cloud-kms/src/types/index.ts
Labels: ready for review

#93 Analytics lib folder
  .changeset/dirty-insects-remain.md
  packages/analytics/.gitignore
  packages/analytics/lib/AnalyticsContext.d.ts
  packages/analytics/lib/AnalyticsContext.d.ts.map
  packages/analytics/lib/AnalyticsContext.js
  packages/analytics/lib/AnalyticsProvider.d.ts
  packages/analytics/lib/AnalyticsProvider.d.ts.map
  packages/analytics/lib/AnalyticsProvider.js
  packages/analytics/lib/index.d.ts
  packages/analytics/lib/index.d.ts.map
  packages/analytics/lib/index.js
  packages/analytics/lib/index.test.js
  packages/analytics/lib/integrations/ga/GA.d.ts
  packages/analytics/lib/integrations/ga/GA.d.ts.map
  packages/analytics/lib/integrations/ga/GA.js
  packages/analytics/lib/integrations/ga/index.d.ts
  packages/analytics/lib/integrations/ga/index.d.ts.map
  packages/analytics/lib/integrations/ga/index.js
  packages/analytics/lib/integrations/ga/loadGA.d.ts
  packages/analytics/lib/integrations/ga/loadGA.d.ts.map
  packages/analytics/lib/integrations/ga/loadGA.js
  packages/analytics/lib/integrations/ga/types.d.ts
  packages/analytics/lib/integrations/ga/types.d.ts.map
  packages/analytics/lib/integrations/ga/types.js
  packages/analytics/lib/integrations/index.d.ts
  packages/analytics/lib/integrations/index.d.ts.map
  packages/analytics/lib/integrations/index.js
  packages/analytics/lib/integrations/segment/Segment.d.ts
  packages/analytics/lib/integrations/segment/Segment.d.ts.map
  packages/analytics/lib/integrations/segment/Segment.js
  packages/analytics/lib/integrations/segment/index.d.ts
  packages/analytics/lib/integrations/segment/index.d.ts.map
  packages/analytics/lib/integrations/segment/index.js
  packages/analytics/lib/integrations/segment/loadSnippet.d.ts
  packages/analytics/lib/integrations/segment/loadSnippet.d.ts.map
  packages/analytics/lib/integrations/segment/loadSnippet.js
  packages/analytics/lib/integrations/segment/types.d.ts
  packages/analytics/lib/integrations/segment/types.d.ts.map
  packages/analytics/lib/integrations/segment/types.js
  packages/analytics/lib/integrations/types.d.ts
  packages/analytics/lib/integrations/types.d.ts.map
  packages/analytics/lib/integrations/types.js
  packages/analytics/lib/types.d.ts
  packages/analytics/lib/types.d.ts.map
  packages/analytics/lib/types.js
  packages/analytics/lib/useAnalytics.d.ts
  packages/analytics/lib/useAnalytics.d.ts.map
  packages/analytics/lib/useAnalytics.js
Labels: ready for review

#90 Use appropriate main branch for actions/checkout
  .github/workflows/publish.yml
Labels: ready for review

#95 Add babel plugin to compile class properties
  .changeset/kind-chicken-appear.md
  packages/analytics/.babelrc
  packages/analytics/lib/index.test.js
  packages/analytics/lib/integrations/ga/GA.js
  packages/analytics/lib/integrations/segment/Segment.js
  packages/analytics/package.json
  yarn.lock
Labels: bug, ready for review
